# Generated by Django 4.0.3 on 2022-03-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_via', models.CharField(choices=[('c/', 'Calle'), ('avd', 'Avenida'), ('plza', 'Plaza')], default='c/', max_length=4)),
                ('nombre', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('ciudad', models.CharField(max_length=50)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=12)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=12)),
            ],
            options={
                'verbose_name': 'Coordenadas',
                'verbose_name_plural': 'Coordenadass',
            },
        ),
        migrations.DeleteModel(
            name='Coordenadas',
        ),
    ]
