# Generated by Django 4.0.3 on 2022-03-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_direccion_delete_coordenadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
    ]
