# Generated by Django 4.0.3 on 2022-04-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_usuario_direccion_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellidos',
            new_name='apellido',
        ),
    ]
